# Generated by Django 4.1.3 on 2022-12-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
    ]
